//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAkhir_Kel02
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadRuangan
    {
        public string id_ruangan { get; set; }
        public string nama_ruangan { get; set; }
        public decimal harga_ruangan { get; set; }
        public string status { get; set; }
    }
}
