//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAkhir_Kel02
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SI_HotelEntities12 : DbContext
    {
        public SI_HotelEntities12()
            : base("name=SI_HotelEntities12")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<ReportMenu_Result> ReportMenu(Nullable<System.DateTime> dari, Nullable<System.DateTime> sampai)
        {
            var dariParameter = dari.HasValue ?
                new ObjectParameter("dari", dari) :
                new ObjectParameter("dari", typeof(System.DateTime));
    
            var sampaiParameter = sampai.HasValue ?
                new ObjectParameter("sampai", sampai) :
                new ObjectParameter("sampai", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReportMenu_Result>("ReportMenu", dariParameter, sampaiParameter);
        }
    }
}
